name: Updates E2E enabled (iOS)
defaults:
  tools:
    yarn: '1.22.22'

on:
  push:
    branches: ['doug/sdk-52-workflow-testing']

jobs:
  setup:
    runs_on: macos-large
    steps:
      - name: Install applesimutils
        id: ios_simulator
        env:
          HOMEBREW_NO_AUTO_UPDATE: "1"
        run: |
          /opt/homebrew/bin/brew tap wix/brew
          /opt/homebrew/bin/brew install applesimutils
          xcrun simctl list
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Set up Updates E2E enabled project
        id: setup
        env:
          UPDATES_HOST: localhost
          UPDATES_PORT: "4747"
        run: |
          yarn --silent ts-node --transpile-only ./packages/expo-updates/e2e/setup/create-eas-project.ts
          ls -la ../updates-e2e
      - name: Build E2E project
        id: build
        working_directory: ../updates-e2e
        run: |
          yarn generate-test-update-bundles
          npx pod-install
          npx detox build -c ios.debug
      - name: Test E2E project
        id: test
        env:
          UPDATES_HOST: localhost
          UPDATES_PORT: "4747"
        working_directory: ../updates-e2e
        run: |
          npx detox test -c ios.debug



